behaviors:
  ShelterSelect:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 409600
      learning_rate: 1e-3
      beta: 0.01
      epsilon: 0.3
      lambd: 0.99
      num_epoch: 5
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.80
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 500000
    time_horizon: 2048
    summary_freq: 5
environment_parameters:
  mass:
    sampler_type: uniform
    sampler_parameters:
      min_value: 0.5
      max_value: 10
  scale:
    sampler_type: uniform
    sampler_parameters:
      min_value: 0.75
      max_value: 3
