behaviors:
  ShelterSelect:
    trainer_type: sac
    hyperparameters:
      batch_size: 10240
      buffer_size: 12000
      learning_rate: 0.0001
      beta: 0.02
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 10
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 1240
      num_layers: 6
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 10
    max_steps: 500000
    time_horizon: 1000
    summary_freq: 1